version: '3'

services:
  mongodb:
    image: mongo:4.4
    container_name: meu-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario_root
      MONGO_INITDB_ROOT_PASSWORD: senha_root
    volumes:
      - ./dados_mongodb:/data/db


# docker exec -it meu-mongodb mongo your-database -u usuario_root -p senha_root --authenticationDatabase admin --eval 'db.createUser({user: "user1", pwd: "password", roles: ["readWrite"]})'
# this command for create a user inside of the container


# docker logs mongodb

# docker exec -it mongodb mongo

# wsl hostname -I

