version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - my-network
    environment:
      MONGO_URI: mongodb://admin:adminpassword@mongo-container:27017/your-database

networks:
  my-network:
    driver: bridge
